removed automapper, updated entities
Boobl1k/dekoffee pull request #24
Opened 2023-05-11 00:12 UTC by Boobl1k

closes 12, closes 23

2023-05-12 11:02 UTC, Focus1337 requested changes

2023-05-12 11:02 UTC, Focus1337 commented on src/Services/Main/Main.Application/Interfaces/ICartService.cs
>  public interface ICartService
Некачественное тестирование. 500 ошибка почти во всех методах контроллера CartController. Ошибка в работе с Owns, Owned.

2023-05-12 19:11 UTC, Boobl1k commented on src/Services/Main/Main.Application/Models/OrderProduct.cs
> +    public Guid Id { get; } = Guid.NewGuid();
orderProduct в данной ветке еще не owned, поэтому поле нужно, будет убрано позже в #25

2023-05-12 19:11 UTC, Boobl1k commented on src/Services/Main/Main.Application/Models/Cart.cs
> +[Owned]
все верно, я так и подразумевал

2023-05-12 19:12 UTC, Boobl1k commented on src/Services/Main/Main.Application/Models/Cart.cs
> +    // ReSharper disable once UnusedMember.Local
это нормальное решение для EF. Пустой конструктор ему необходим, но нигде явным образом он не используется

2023-05-12 19:13 UTC, Boobl1k commented on src/Services/Main/Main.Application/Models/Order.cs
> +            OrderStatus.Accepted => "Обрабатывается",
\+

2023-05-12 19:17 UTC, Focus1337 commented on src/Services/Main/Main.Application/Models/Cart.cs
> +[Owned]
Почему в данной таблице должно быть поле `Cart_TotalSum`?

2023-05-16 20:52 UTC, Boobl1k commented on src/Services/Main/Main.Application/Models/Cart.cs
> +[Owned]
потому что я решил что нет смысла иметь корзину в отдельной таблице, потому что корзина не сущность, а тип который принадлежит одному юзеру и никогда не будет принадлежать другому

2023-05-16 20:55 UTC, Boobl1k commented on src/Services/Main/Main.Application/Models/Invoice.cs
> +[Owned]
будет решено в следующем пр

2023-05-16 21:02 UTC, Boobl1k commented on src/Services/Main/Main.Web/Dto/Order/DisplayOrderDto.cs
> +    public static DisplayOrderDto FromEntity(Application.Models.Order entity) => new()
как правильное решение я бы рассмотрел написание отдельного маппер-класса вместо методов внутри дто и отказаться от библиотек для маппинга

принято решение оставить как есть

2023-05-16 21:27 UTC, Boobl1k commented on src/Services/Main/Main.Application/Interfaces/ICartService.cs
>  public interface ICartService
будет исправлено в следующем пр

2023-05-17 11:38 UTC, Focus1337 commented on src/Services/Main/Main.Application/Models/Cart.cs
> +[Owned]
Это звучит как хорошее решение, но в случае корзины неправильно.

С технологической точки зрения
https://stackoverflow.com/a/61706893

С точки зрения DDD
https://stackoverflow.com/a/70458223

Или вот здесь расписан дизайн eCommerce системы с учетом DDD
https://medium.com/swlh/microservices-poweredby-domain-driven-design-6160fcac5409

2023-05-17 17:57 UTC, Focus1337 commented on src/Services/Main/Main.Application/Models/Cart.cs
> +[Owned]
Оставляем давай так же. Не будем менять.
Просто снова к сведению берем.

2023-05-17 17:59 UTC, merged